### ISSUE TITLE
UWP

### ISSUE THREAD

**Issue by nnnlog** [KiwiTalk/loco.rs#37]
#21 의 Status Code 30은 XVC 코드 문제
* UWP의 XVC 생성 시드는 PC와 약간 다름

UWP의 XVC는
```
Hash algorithm: sha512
```
```
SIMON|{UserAgent}|EDWARD|{EMAIL}|{UUID}
```

* 또한, Agent (KakaoTalk[KT]) 버전도 다름
UWP의 Agent는 현재(2020.07.21 기준)
```
KT/1.2.1 Uw/10.0.18363 ko
```

UWP 앱에 사용되는 HTTP Header의 A 값은 현재
```
uwp/1.2.1/ko
```

UWP 앱의 UUID는 PC 카카오톡과 다르게 해싱값으로 보임

* 특정 http 요청에 담긴 `Kakao: Talk` 헤더 (이모티콘 다운로드 시에 사용)

**Comment by JellyBrick** [comment]
#21 과 중복
