### ISSUE TITLE
카카오톡 운영정책 변경

### ISSUE THREAD

**Issue by DeltaLaboratory** [KiwiTalk/loco.rs#59]
[2021년 12월 7일부터 적용되는 개정된 운영정책](http://kko.to/KQULO7Z4B)에 의하면,

- 프로그램코드 역분석을 통하여 얻은 정보를 제 3 자에게 제공·공개하는 행위 [P37L4]
- 카카오가 허용하지 않은 비정상적인 프로그램 등을 이용하여 카카오톡의 프로토콜·API 등을 부정하게
호출하는 행위 [P37L9]

등을 금지하고 있습니다.
상기 운영정책에 따르면, 이 라이브러리는 카카오 운영정책에 위배됩니다.
이에 따른 대책이 있으시거나, 이 라이브러리를 삭제할 의향이 있으십니까?

**Comment by JellyBrick** [comment]
- [P37L4]. 해당 API Wrapper는 역분석을 통하여 정보를 얻지 않았습니다.
- [P37L9]. `loco.rs` 는 API Wrapper로써, 해당 wrapper를 사용하는 사용자에게 책임이 있습니다. (`Apache 2.0 License`)

따라서 키위톡 팀의 방침은 현재와 동일합니다.
